import {
  Crown,
  Briefcase,
  Code,
  GraduationCap,
  Award,
  Compass,
  User,
} from "lucide-react";
import { Kingdom, KingdomName } from "./gameData";
import { color } from "framer-motion";

export const aboutMe = {
  name: "Sinomtha Mzamo",
  title: "Full-Stack Developer & Cloud Engineer",
  tagline:
    "Building accessible, user-first solutions from design to deployment",
  bio: "Full-stack developer and certified Cloud Practitioner with proven experience in billing system integrations, patient-facing healthcare applications. Adept at bridging technical gaps and enhancing team productivity across microservices, API development, building native mobile interfaces, deploying cloud solutions, and front-end development. Improved MVP output and API lifecycle services.",
  contact: {
    email: "sinomtha.dev@gmail.com",
    phone: "+27 68 334 3547",
    location: "Cape Town, South Africa",
    linkedin: "linkedin.com/in/sinomtha",
    github: "github.com/sinomtha",
  },
  skills: {
    fullStack: ["React.js", "Python", "Java"],
    cloudDevOps: ["AWS", "CI/CD", "Docker"],
    databases: ["PostgreSQL", "MongoDB", "Firebase"],
    softSkills: ["Leadership", "Mentoring", "Agile"],
  },
};

export const kingdoms: Kingdom[] = [
  {
    id: "projects",
    name: KingdomName.Projects,
    description: "Featured creations and builds",
    icon: Code,
    colour: "from-cyan-500 to-teal-600",
    position: { angle: 0, distance: 240 },
    missions: [
      {
        id: "full-stack-dev",
        title: "Student Accommodation Management Platform",
        description:
          "Designed and developed a comprehensive booking and property management system for a student accommodation company seeking to retain residents efficiently.",
        details: [
          "Conducted requirements gathering sessions and translated business needs into technical specifications",
          "Delivered iterative prototypes with Figma mockups for stakeholder approval",
          "Provided technical documentation and admin training for seamless system handoff",
          "Built responsive React-based booking platform using Vite, React Hook Form, and Zod for robust form validation",
          "Implemented real-time administrative dashboard with property analytics, occupancy tracking, tenant directory, and broadcast messaging capabilities",
          "Integrated Supabase for authentication, PostgreSQL database management, and secure file storage for tenant documents",
          "Used ReactQuery for efficient server state management and optimistic UI updates",
          "Reduced booking processing time from 48 hours to under 5 minutes through digital automation",
          "Created an admin-facing dashboard to visualise applications and student data, improving real-time visibility and reducing manual tracking.",
          "Created exportable analytics and reporting features for financial reconciliation and capacity planning",
        ],
        date: "Aug 20254 - Present",
        technologies: ["React", "Tailwind CSS", "Zod", "Supabase"],
        unlocked: false,
        gameType: "memory",
        gameData: {
          crossword: [
            {
              word: "AGILE",
              hint: "Iterative way of building software with quick feedback cycles (Scrum/Kanban)",
            },
            {
              word: "FIGMA",
              hint: "Popular collaborative UI/UX design and prototyping tool",
            },
            {
              word: "ANGULAR",
              hint: "TypeScript-based front-end framework maintained by Google",
            },
            {
              word: "AWS",
              hint: "Amazon’s cloud platform for hosting, storage, databases, and more",
            },
          ],
          architectureLayers: [
            { layerPosition: 0, description: "refrigerant readings", icon: "" },
            { layerPosition: 1, description: "database", icon: "" },
            { layerPosition: 2, description: "monitoring dashboard", icon: "" },
          ],
          matchThree: [
            { colour: "cornflowerblue", icon: "TypeScript" },
            { colour: "darksalmon", icon: "Figma" },
            { colour: "blue", icon: "Docker" },
            { colour: "crimson", icon: "Angular" },
            { colour: "green", icon: "Node" },
            { colour: "dodgerblue", icon: "Cloud" },
          ],
          memoryMatch: ["React", "TypeScript", "Sprint", "QA", "SDK", "API"],
        },
        targetScore: 1000,
      },
      {
        id: "debt-mgmt",
        title: "Bhala Edolweni - Debtor Management",
        description:
          "Full-stack platform for small businesses to track debtors.",
        details: [
          "Developed headless and React frontends integrated with a REST API, enabling flexible and scalable client-server interactions.",
          "Implemented comprehensive CRUD operations, multi-user role management (Admin, Agent, Debtor), and data persistence with CORS handling.",
          "Implemented Test-Driven Development (TDD) and Behavior-Driven Development (BDD) practices using unittest and pytest, ensuring reliable, well-tested, and maintainable code.",
          "Enhanced system security with AES encryption for sensitive debtor and payment data, ensuring compliance with data protection standards.",
          "Transitioning the backend to Kotlin for enhanced scalability and performance, leveraging Kotlin Multiplatform for cross-platform adaptability. ",
        ],
        technologies: [
          "React.js",
          "Python",
          "REST API",
          "MVC",
          "Kotlin",
          "KMP",
        ],
        links: [{ label: "View Project", url: "#" }],
        date: "2024",
        unlocked: false,
        gameType: "memory",
        gameData: {
          crossword: [
            { word: "KOTLIN", hint: "" },
            { word: "REACT", hint: "" },
            { word: "DEBTOR", hint: "" },
            { word: "PYTHON", hint: "" },
          ],
          architectureLayers: [
            { layerPosition: 0, description: "refrigerant readings", icon: "" },
            { layerPosition: 1, description: "database", icon: "" },
            { layerPosition: 2, description: "monitoring dashboard", icon: "" },
          ],
          matchThree: [
            { colour: "blueviolet", icon: "Kotlin" },
            { colour: "mediumpurple", icon: "React" },
            { colour: "salmon", icon: "Python" },
            { colour: "limegreen", icon: "Invoice" },
            { colour: "cornflowerblue", icon: "SQL" },
            { colour: "crimson", icon: "Server" },
          ],
          memoryMatch: ["React", "Kotlin", "API", "Auth", "Invoice", "Form"],
        },
        targetScore: 1000,
      },
      {
        id: "ai-coach",
        title: "Vuka Coach - AI Interview Coaching Platform",
        description:
          "AI-powered interview coaching platform addressing South Africa's youth unemployment (46.6% rate).",
        details: [
          "Integrated Google Gemini 2.5 Flash, Groq Whisper, and Google Cloud TTS for personalized question generation, speech recognition, and voice feedback.",
          "Implemented real-time voice practice with instant AI analysis on content, delivery, and professionalism.",
          "Developed CV/​JD parsing to generate tailored questions and STAR method stories for behavioral interviews.",
          "Created comprehensive performance reports with actionable insights and metrics (clarity, relevance, confidence).",
          "Designed mobile-first, data-efficient UI optimised for South African context (<5MB per session, low-end device support).",
          "Architected scalable FastAPI + React solution with session management and multi-AI model orchestration.",
        ],
        technologies: ["React.js", "FastAPI", "Gemini", "Groq", "Python"],
        links: [{ label: "View Project", url: "#" }],
        date: "2025",
        unlocked: false,
        gameType: "memory",
        gameData: {
          crossword: [
            { word: "STT", hint: "Speech To Text Acronym" },
            { word: "TTS", hint: "Text To Speech Acronym" },
            { word: "MODEL", hint: "" },
            { word: "PROMPT", hint: "" },
          ],
          architectureLayers: [
            { layerPosition: 0, description: "refrigerant readings", icon: "" },
            { layerPosition: 1, description: "database", icon: "" },
            { layerPosition: 2, description: "monitoring dashboard", icon: "" },
          ],
          matchThree: [
            { colour: "blueviolet", icon: "AI" },
            { colour: "mediumpurple", icon: "React" },
            { colour: "salmon", icon: "Briefcase" },
            { colour: "limegreen", icon: "Voice" },
            { colour: "cornflowerblue", icon: "Python" },
            { colour: "crimson", icon: "Gemini" },
          ],
          memoryMatch: [
            "React",
            "AI",
            "Voice",
            "Python",
            "Briefcase",
            "Gemini",
          ],
        },
        targetScore: 1000,
      },
      {
        id: "dha-babs-ux",
        title: "UX Revamp - DHA Appointment Booking System",
        description:
          "End-to-end UX redesign solving critical usability issues with the Department of Home Affairs Branch Appointment Booking System",
        details: [
          "Designed a landing page to introduce the platform, highlight features, and clarify available services.",
          "Enhanced group booking feature visibility through improved layout and visual hierarchy.",
          "Implemented progress indicators to guide users through the booking process.",
          "Added alternative branch suggestions for failed searches to reduce user frustration.",
          "•Improved navigation and data persistence, enabling seamless backtracking.",
          "Ensured full cross-browser and cross-device support, including Safari on iOS, addressing limitations in the original government solution.",
        ],
        technologies: ["Angular", "TypeScript", "Cursor", "Tailwind CSS"],
        links: [{ label: "View Project", url: "#" }],
        date: "2025",
        unlocked: false,
        gameType: "memory",
        gameData: {
          crossword: [
            { word: "CURSOR", hint: "Speech To Text Acronym" },
            { word: "VIBE", hint: "Text To Speech Acronym" },
            { word: "MODEL", hint: "" },
            { word: "PROMPT", hint: "" },
          ],
          architectureLayers: [
            { layerPosition: 0, description: "refrigerant readings", icon: "" },
            { layerPosition: 1, description: "database", icon: "" },
            { layerPosition: 2, description: "monitoring dashboard", icon: "" },
          ],
          matchThree: [
            { colour: "blueviolet", icon: "AI" },
            { colour: "mediumpurple", icon: "Angular" },
            { colour: "salmon", icon: "UX" },
            { colour: "limegreen", icon: "Cursor" },
            { colour: "cornflowerblue", icon: "RSA" },
            { colour: "crimson", icon: "TypeScript" },
          ],
          memoryMatch: ["Angular", "AI", "Cursor", "UX", "RSA", "Code"],
        },
        targetScore: 1000,
      },
      {
        id: "crm-cloud-aws",
        title: "Personal Portfolio & CRM Dashboard",
        description:
          "Deployed portfolio with secure admin dashboard, serverless backend, authenticated admin flows, and email notifications via SES.",
        details: [
          "Built a fully deployed portfolio showcasing projects and blog posts, with an integrated secure dashboard for managing content, updating my CV and avatar, and responding to messages without modifying code.",
          "Designed system architecture, responsive UI wireframes and prototypes in Figma and Miro, focusing on usability and maintainability.",
          "Developed and deployed a responsive Angular frontend via S3 and CloudFront CDN.",
          "Implemented backend APIs using Lambda, API Gateway, DynamoDB, and CloudFormation.",
          "Secured dashboard access with AWS Cognito for authentication and authorisation.",
          "Integrated AWS SES and Gmail API for contact form notifications and direct email replies.",
        ],
        technologies: [
          "Angular",
          "TypeScript",
          "Cursor",
          "Tailwind CSS",
          "Gmail API",
          "AWS",
        ],
        links: [{ label: "View Project", url: "#" }],
        date: "2025",
        unlocked: false,
        gameType: "memory",
        gameData: {
          crossword: [
            { word: "CLOUD", hint: "Speech To Text Acronym" },
            { word: "AWS", hint: "Text To Speech Acronym" },
            { word: "CONSOLE", hint: "" },
            { word: "HOST", hint: "" },
          ],
          architectureLayers: [
            { layerPosition: 0, description: "refrigerant readings", icon: "" },
            { layerPosition: 1, description: "database", icon: "" },
            { layerPosition: 2, description: "monitoring dashboard", icon: "" },
          ],
          matchThree: [
            { colour: "blueviolet", icon: "Upload" },
            { colour: "mediumpurple", icon: "Editing" },
            { colour: "salmon", icon: "Dashboard" },
            { colour: "limegreen", icon: "Mail" },
            { colour: "cornflowerblue", icon: "Lambda" },
            { colour: "crimson", icon: "Dynamodb" },
          ],
          memoryMatch: ["Cloud", "Dynamodb", "AWS", "S3", "IAM", "Cert"],
        },
        targetScore: 1000,
      },
      {
        id: "routepool-mobile",
        title: "RoutePool - Carpooling Platform",
        description:
          "Mobile app connecting drivers and passengers on shared routes to reduce traffic congestion in Cape Town.",
        details: [
          "Designed ride-matching user flows to reduce single-occupancy vehicles, leveraging HOV lane incentives in Cape Town to address traffic congestion and spatial inequality.",
          "Conducted usability evaluations and team feedback loops, iterating designs for simplicity, clarity, and accessibility.",
          "Built a Flutter mobile app connecting drivers and passengers on shared daily routes, with authentication, profiles, and ride posting/​matching based on design artifacts.",
          "Integrated Google Maps API for route display, navigation, and basic ride tracking.",
          "Implemented real-time updates with push notifications and in-app chat for smoother communication between users",
          "Added basic safety and trust features, including an SOS button, user reviews, and trust ratings.",
          "Supported digital payments and fare calculations for transparent cost-sharing.",
          "Developed a Kotlin/​Spring Boot REST API backend with PostgreSQL, deployed to AWS, handling ride data, user profiles, and payments.",
        ],
        technologies: [
          "Figma",
          "Miro",
          "UX Design",
          "Flutter",
          "Kotlin",
          "PostgreSQL",
        ],
        links: [{ label: "View Project", url: "#" }],
        date: "2025",
        unlocked: false,
        gameType: "memory",
        gameData: {
          crossword: [
            { word: "CLOUD", hint: "Speech To Text Acronym" },
            { word: "AWS", hint: "Text To Speech Acronym" },
            { word: "CONSOLE", hint: "" },
            { word: "HOST", hint: "" },
          ],
          architectureLayers: [
            { layerPosition: 0, description: "refrigerant readings", icon: "" },
            { layerPosition: 1, description: "database", icon: "" },
            { layerPosition: 2, description: "monitoring dashboard", icon: "" },
          ],
          matchThree: [
            { colour: "blueviolet", icon: "Upload" },
            { colour: "mediumpurple", icon: "Editing" },
            { colour: "salmon", icon: "Dashboard" },
            { colour: "limegreen", icon: "Mail" },
            { colour: "cornflowerblue", icon: "Lambda" },
            { colour: "crimson", icon: "Dynamodb" },
          ],
          memoryMatch: ["Cloud", "Dynamodb", "AWS", "S3", "IAM", "Cert"],
        },
        targetScore: 1000,
      },
      {
        id: "notes-scraper",
        title: "NoteWatch - Confluence Activity Analytics & Search",
        description:
          "Co-developed a tool to scrape Confluence pages and index intern notes to generate activity analytics and a heatmap-style view of contributions.",
        details: [
          "Co-developed NoteWatch, a Confluence activity analytics and search tool to improve visibility into intern contributions and knowledge sharing.",
          "Scraped and indexed Confluence pages using Atlassian APIs and web scraping techniques to extract structured note content and metadata.",
          "Built a searchable notes repository enabling fast lookup of intern documentation, meeting notes, and project updates.",
          "Designed and implemented activity analytics dashboards, surfacing contribution frequency, page edits, and collaboration patterns.",
          "Developed a heatmap-style visualization to highlight high-activity periods and identify engagement trends over time.",
          "Implemented a Node.js backend to handle data ingestion, processing, and indexing for analytics generation.",
          "Created an interactive Angular frontend to display insights, search results, and contribution metrics in a user-friendly UI.",
          "Improved team knowledge accessibility by enabling quick discovery of key notes and reducing time spent searching across Confluence spaces.",
        ],
        technologies: [
          "Webscraping",
          "Atlassian REST API",
          "Angular",
          "Figma",
          "Node.js",
        ],
        links: [{ label: "View Project", url: "#" }],
        date: "2025",
        unlocked: false,
        gameType: "memory",
        gameData: {
          crossword: [
            { word: "CLOUD", hint: "Speech To Text Acronym" },
            { word: "AWS", hint: "Text To Speech Acronym" },
            { word: "CONSOLE", hint: "" },
            { word: "HOST", hint: "" },
          ],
          architectureLayers: [
            { layerPosition: 0, description: "refrigerant readings", icon: "" },
            { layerPosition: 1, description: "database", icon: "" },
            { layerPosition: 2, description: "monitoring dashboard", icon: "" },
          ],
          matchThree: [
            { colour: "blueviolet", icon: "Upload" },
            { colour: "mediumpurple", icon: "Editing" },
            { colour: "salmon", icon: "Dashboard" },
            { colour: "limegreen", icon: "Mail" },
            { colour: "cornflowerblue", icon: "Lambda" },
            { colour: "crimson", icon: "Dynamodb" },
          ],
          memoryMatch: ["Cloud", "Dynamodb", "AWS", "S3", "IAM", "Cert"],
        },
        targetScore: 1000,
      },
      {
        id: "burn-aft-read",
        title: "Burn After Reading",
        description:
          "View-once encrypted messaging app with symmetric encryption and ephemeral data handling.",
        details: [
          "Built Burn After Reading, a security-first view-once encrypted messaging web app designed for sending sensitive messages that self-destruct after being opened.",
          "Implemented a complete user flow: compose message → set password → generate shareable link → recipient decrypts and views once.",
          "Developed symmetric encryption logic to securely encrypt/decrypt message content, ensuring plaintext is never stored server-side.",
          "Designed ephemeral data handling, automatically deleting messages after first successful access to prevent replays and re-reads.",
          "Added browser-side security controls to reduce leakage, including disabling screenshots/recording attempts and blocking microphone/camera access.",
          "Integrated Text-to-Speech (TTS) support for accessibility while maintaining one-time viewing restrictions.",
          "Built the frontend using Angular + TypeScript, focusing on a minimal, user-friendly interface for secure message sharing.",
          "Deployed the application on AWS (Elastic Beanstalk, EC2, S3) and performed EC2 patching to maintain secure infrastructure.",
          "Applied encryption-first design principles to strengthen confidentiality and minimize exposure of sensitive data.",
        ],
        technologies: [
          "TypeScript",
          "Elastic Beanstalk",
          "Angular",
          "EC2",
          "S3",
          "Encryption",
        ],
        links: [{ label: "View Project", url: "#" }],
        date: "2025",
        unlocked: false,
        gameType: "memory",
        gameData: {
          crossword: [
            { word: "CLOUD", hint: "Speech To Text Acronym" },
            { word: "AWS", hint: "Text To Speech Acronym" },
            { word: "CONSOLE", hint: "" },
            { word: "HOST", hint: "" },
          ],
          architectureLayers: [
            { layerPosition: 0, description: "refrigerant readings", icon: "" },
            { layerPosition: 1, description: "database", icon: "" },
            { layerPosition: 2, description: "monitoring dashboard", icon: "" },
          ],
          matchThree: [
            { colour: "blueviolet", icon: "Upload" },
            { colour: "mediumpurple", icon: "Editing" },
            { colour: "salmon", icon: "Dashboard" },
            { colour: "limegreen", icon: "Mail" },
            { colour: "cornflowerblue", icon: "Lambda" },
            { colour: "crimson", icon: "Dynamodb" },
          ],
          memoryMatch: ["Cloud", "Dynamodb", "AWS", "S3", "IAM", "Cert"],
        },
        targetScore: 1000,
      },
      {
        id: "clu-connect",
        title: "Club Connect Website",
        description:
          "A community website for WeThinkCode_ Durban campus clubs to showcase events, activities, and student engagement.",
        details: [
          "Designed and implemented a testimonial submission feature, allowing verified users to share feedback and experiences.",
          "Built secure backend functionality using PHP and PostgreSQL, ensuring reliable data storage and structured testimonial management.",
          "Integrated frontend and backend components through a REST API, supporting clean separation of concerns and scalable architecture.",
          "Developed a responsive UI using HTML, CSS, JavaScript, and Bootstrap, improving accessibility across mobile and desktop devices.",
          "Applied full-stack development practices including form validation, API consumption, and database-driven content rendering.",
          "Collaborated in a small development team, iterating features based on feedback and aligning functionality with user needs.",
          "Submitted the project to the New Type Works Hacks Hackathon, demonstrating end-to-end delivery under a structured deadline.",
        ],
        technologies: [
          "PHP",
          "JavaScript",
          "Drive API",
          "PostgreSQL",
          "Bootstrap",
          "HTML",
          "CSS",
        ],
        links: [{ label: "View Project", url: "#" }],
        date: "2025",
        unlocked: false,
        gameType: "memory",
        gameData: {
          crossword: [
            { word: "CLOUD", hint: "Speech To Text Acronym" },
            { word: "AWS", hint: "Text To Speech Acronym" },
            { word: "CONSOLE", hint: "" },
            { word: "HOST", hint: "" },
          ],
          architectureLayers: [
            { layerPosition: 0, description: "refrigerant readings", icon: "" },
            { layerPosition: 1, description: "database", icon: "" },
            { layerPosition: 2, description: "monitoring dashboard", icon: "" },
          ],
          matchThree: [
            { colour: "blueviolet", icon: "Upload" },
            { colour: "mediumpurple", icon: "Editing" },
            { colour: "salmon", icon: "Dashboard" },
            { colour: "limegreen", icon: "Mail" },
            { colour: "cornflowerblue", icon: "Lambda" },
            { colour: "crimson", icon: "Dynamodb" },
          ],
          memoryMatch: ["Cloud", "Dynamodb", "AWS", "S3", "IAM", "Cert"],
        },
        targetScore: 1000,
      },
    ],
  },
  {
    id: "experience",
    name: KingdomName.Experience,
    description: "Professional journey and roles",
    icon: Briefcase,
    colour: "from-amber-500 to-orange-600",
    position: { angle: 60, distance: 240 },
    missions: [
      {
        id: "software-dev-intern",
        title: "Software Developer Intern",
        description: "Safety IO - Full-stack development internship",
        details: [
          "Migrated Bamboo runner to Bitbucket Pipelines, reducing deployment errors by 25% and streamlining CI/CD workflows",
          "Built full-stack applications with Angular, TypeScript, and PostgreSQL, strengthening expertise in scalable front-end and relational database integration",
          "Analysed Datadog logs to identify performance bottlenecks, improving system uptime and demonstrating strong debugging and observability skills",
          "Co-developed a Confluence analytics tool with activity heatmaps and advanced search functionality, adding data-driven insights for stakeholders",
          "Selected and assessed trade-offs between design patterns such as Factory and Builder to improve system design, demonstrating solid software architecture judgment and maintainability practices",
          "Enhanced team communication pipelines by integrating Bitbucket and Microsoft Teams webhooks automated with Ansible to continuously notify developers of activity on critical branches, strengthening collaboration and supporting a proactive DevOps culture",
          "Refactored and streamlined stylesheets by migrating to modular SCSS and removing legacy code smells, leading to cleaner structure, easier maintenance, and improved front-end performance.",
        ],
        date: "Jan 2025 - Sep 2025",
        unlocked: false,
        gameType: "memory",
        gameData: {
          crossword: [
            {
              word: "AGILE",
              hint: "Iterative way of building software with quick feedback cycles (Scrum/Kanban)",
            },
            {
              word: "FIGMA",
              hint: "Popular collaborative UI/UX design and prototyping tool",
            },
            {
              word: "ANGULAR",
              hint: "TypeScript-based front-end framework maintained by Google",
            },
            {
              word: "AWS",
              hint: "Amazon’s cloud platform for hosting, storage, databases, and more",
            },
          ],
          architectureLayers: [
            { layerPosition: 0, description: "refrigerant readings", icon: "" },
            { layerPosition: 1, description: "database", icon: "" },
            { layerPosition: 2, description: "monitoring dashboard", icon: "" },
          ],
          matchThree: [
            { colour: "cornflowerblue", icon: "TypeScript" },
            { colour: "darksalmon", icon: "Figma" },
            { colour: "blue", icon: "Docker" },
            { colour: "crimson", icon: "Angular" },
            { colour: "green", icon: "Node" },
            { colour: "dodgerblue", icon: "Cloud" },
          ],
          memoryMatch: ["React", "TypeScript", "Sprint", "QA", "SDK", "API"],
        },
        targetScore: 1000,
      },
      {
        id: "coding-exp-trainer",
        title: "Coding Expert",
        description: "Outlier.ai - Freelance AI Trainer",
        details: [
          "Reviewed and optimized AI-generated code in JavaScript, Python, Java, and TypeScript for accuracy, clarity, and efficiency, ensuring high-quality deliverables under tight deadlines",
          "Delivered detailed, actionable feedback on AI outputs to improve correctness, tone, and alignment with project guidelines.",
          "Completed over 100 coding tasks in one month, generating more than R25,000 in earnings, reflecting high-quality, consistent work within tight deadlines.",
          "Designed coding challenges and structured solutions to strengthen AI reasoning and problem-solving.",
          "Applied annotation guidelines consistently, resolving ambiguous edge cases with sound judgment.",
          "•Gained practical experience with Reinforcement Learning with Human Feedback (RLHF) workflows and structured annotation.",
        ],
        date: "Aug 2024 - Present",
        unlocked: false,
        gameType: "memory",
        gameData: {
          crossword: [
            {
              word: "AGILE",
              hint: "Iterative way of building software with quick feedback cycles (Scrum/Kanban)",
            },
            {
              word: "FIGMA",
              hint: "Popular collaborative UI/UX design and prototyping tool",
            },
            {
              word: "ANGULAR",
              hint: "TypeScript-based front-end framework maintained by Google",
            },
            {
              word: "AWS",
              hint: "Amazon’s cloud platform for hosting, storage, databases, and more",
            },
          ],
          architectureLayers: [
            { layerPosition: 0, description: "refrigerant readings", icon: "" },
            { layerPosition: 1, description: "database", icon: "" },
            { layerPosition: 2, description: "monitoring dashboard", icon: "" },
          ],
          matchThree: [
            { colour: "cornflowerblue", icon: "TypeScript" },
            { colour: "darksalmon", icon: "Figma" },
            { colour: "blue", icon: "Docker" },
            { colour: "crimson", icon: "Angular" },
            { colour: "green", icon: "Node" },
            { colour: "dodgerblue", icon: "Cloud" },
          ],
          memoryMatch: ["React", "TypeScript", "Sprint", "QA", "SDK", "API"],
        },
        targetScore: 1000,
      },
      {
        id: "data-sci-intern",
        title: "Data Science Intern",
        description:
          "CodSoft - A structured internship focused on applying data science principles through hands-on machine learning projects",
        details: [
          "Built predictive and classification models using Python, Pandas, NumPy, and Scikit-learn on datasets such as Titanic Survival Prediction, Movie Rating Prediction, and Iris Flower Classification.",
          "Applied data preprocessing, feature engineering, and model evaluation techniques to improve prediction accuracy and interpret results.",
          "Developed practical understanding of regression and classification algorithms, including Logistic Regression, Decision Trees, and Random Forests.",
          "Strengthened data visualization and reporting skills using Matplotlib and Seaborn for clear result communication.",
          "Gained hands-on exposure to sales forecasting and fraud detection through additional applied projects, deepening understanding of real-world data-driven decision making.",
        ],
        date: "Apr 2024 - Present",
        unlocked: false,
        gameType: "memory",
        gameData: {
          crossword: [
            {
              word: "AGILE",
              hint: "Iterative way of building software with quick feedback cycles (Scrum/Kanban)",
            },
            {
              word: "FIGMA",
              hint: "Popular collaborative UI/UX design and prototyping tool",
            },
            {
              word: "ANGULAR",
              hint: "TypeScript-based front-end framework maintained by Google",
            },
            {
              word: "AWS",
              hint: "Amazon’s cloud platform for hosting, storage, databases, and more",
            },
          ],
          architectureLayers: [
            { layerPosition: 0, description: "refrigerant readings", icon: "" },
            { layerPosition: 1, description: "database", icon: "" },
            { layerPosition: 2, description: "monitoring dashboard", icon: "" },
          ],
          matchThree: [
            { colour: "cornflowerblue", icon: "TypeScript" },
            { colour: "darksalmon", icon: "Figma" },
            { colour: "blue", icon: "Docker" },
            { colour: "crimson", icon: "Angular" },
            { colour: "green", icon: "Node" },
            { colour: "dodgerblue", icon: "Cloud" },
          ],
          memoryMatch: ["React", "TypeScript", "Sprint", "QA", "SDK", "API"],
        },
        targetScore: 1000,
      },
    ],
  },
  {
    id: "skills",
    name: KingdomName.Skills,
    description: "Technical abilities and tools",
    icon: Award,
    colour: "from-purple-500 to-indigo-600",
    position: { angle: 120, distance: 240 },
    missions: [
      {
        id: "backend-apis",
        title: "Backend & APIs",
        description: "Server-side technologies and integrations",
        details: [
          "Node.js",
          "Java",
          "Kotlin",
          "Spring Boot",
          "Python",
          "PostgreSQL",
          "REST",
        ],
        unlocked: false,
        gameType: "memory",
        gameData: {
          crossword: [
            {
              word: "SOURCE",
              hint: "Iterative way of building software with quick feedback cycles (Scrum/Kanban)",
            },
            {
              word: "CODE",
              hint: "Instructions written in a programming language to build software",
            },
            {
              word: "SERVER",
              hint: "A computer or system that provides data or services to other computers",
            },
            {
              word: "API",
              hint: "A set of rules that allows different software systems to communicate",
            },
          ],
          architectureLayers: [
            { layerPosition: 0, description: "", icon: "" },
            { layerPosition: 1, description: "", icon: "" },
            { layerPosition: 2, description: "", icon: "" },
          ],
          matchThree: [
            { colour: "mediumpurple", icon: "Server" },
            { colour: "green", icon: "Node" },
            { colour: "crimson", icon: "JSON" },
            { colour: "cornflowerblue", icon: "PGSQL" },
            { colour: "darkorange", icon: "Java" },
          ],
          memoryMatch: ["Node", "Java", "System", "SQL", "REST", "GraphQL"],
        },
        targetScore: 1000,
      },
      {
        id: "frontend-web",
        title: "Frontend | Web Development",
        description: "Frontend technologies, frameworks and integrations",
        details: [
          "Angular",
          "React",
          "Redux",
          "HTML",
          "CSS",
          "TypeScript",
          "JavaScript",
          "Tailwind CSS",
          "SCSS",
          "Bootstrap",
        ],
        unlocked: false,
        gameType: "memory",
        gameData: {
          crossword: [
            {
              word: "DIV",
              hint: "Iterative way of building software with quick feedback cycles (Scrum/Kanban)",
            },
            {
              word: "TAG",
              hint: "Instructions written in a programming language to build software",
            },
            {
              word: "CONST",
              hint: "A computer or system that provides data or services to other computers",
            },
            {
              word: "CURLY",
              hint: "A set of rules that allows different software systems to communicate",
            },
          ],
          architectureLayers: [
            { layerPosition: 0, description: "", icon: "" },
            { layerPosition: 1, description: "", icon: "" },
            { layerPosition: 2, description: "", icon: "" },
          ],
          matchThree: [
            { colour: "mediumpurple", icon: "Server" },
            { colour: "green", icon: "Node" },
            { colour: "crimson", icon: "JSON" },
            { colour: "cornflowerblue", icon: "PGSQL" },
            { colour: "darkorange", icon: "Java" },
          ],
          memoryMatch: ["Node", "Java", "System", "SQL", "REST", "GraphQL"],
        },
        targetScore: 1000,
      },
      {
        id: "ux-ui-design",
        title: "UX/UI design",
        description: "UX/UI Design technologies, tools and integrations",
        details: [
          "Figma",
          "Miro",
          "Prototyping",
          "Wireframing",
          "Gamification",
        ],
        unlocked: false,
        gameType: "memory",
        gameData: {
          crossword: [
            {
              word: "DIV",
              hint: "Iterative way of building software with quick feedback cycles (Scrum/Kanban)",
            },
            {
              word: "TAG",
              hint: "Instructions written in a programming language to build software",
            },
            {
              word: "CONST",
              hint: "A computer or system that provides data or services to other computers",
            },
            {
              word: "CURLY",
              hint: "A set of rules that allows different software systems to communicate",
            },
          ],
          architectureLayers: [
            { layerPosition: 0, description: "", icon: "" },
            { layerPosition: 1, description: "", icon: "" },
            { layerPosition: 2, description: "", icon: "" },
          ],
          matchThree: [
            { colour: "mediumpurple", icon: "Server" },
            { colour: "green", icon: "Node" },
            { colour: "crimson", icon: "JSON" },
            { colour: "cornflowerblue", icon: "PGSQL" },
            { colour: "darkorange", icon: "Java" },
          ],
          memoryMatch: ["Node", "Java", "System", "SQL", "REST", "GraphQL"],
        },
        targetScore: 1000,
      },
      {
        id: "programming",
        title: "Programming Languages",
        description: "Functional and OOP Languages",
        details: ["C#", "Java", "Python", "TypeScript", "JavaScript", "Kotlin"],
        unlocked: false,
        gameType: "memory",
        gameData: {
          crossword: [
            {
              word: "DIV",
              hint: "Iterative way of building software with quick feedback cycles (Scrum/Kanban)",
            },
            {
              word: "TAG",
              hint: "Instructions written in a programming language to build software",
            },
            {
              word: "CONST",
              hint: "A computer or system that provides data or services to other computers",
            },
            {
              word: "CURLY",
              hint: "A set of rules that allows different software systems to communicate",
            },
          ],
          architectureLayers: [
            { layerPosition: 0, description: "", icon: "" },
            { layerPosition: 1, description: "", icon: "" },
            { layerPosition: 2, description: "", icon: "" },
          ],
          matchThree: [
            { colour: "mediumpurple", icon: "Server" },
            { colour: "green", icon: "Node" },
            { colour: "crimson", icon: "JSON" },
            { colour: "cornflowerblue", icon: "PGSQL" },
            { colour: "darkorange", icon: "Java" },
          ],
          memoryMatch: ["Node", "Java", "System", "SQL", "REST", "GraphQL"],
        },
        targetScore: 1000,
      },
      {
        id: "ai-modern-tools",
        title: "AI & Modern Tooling",
        description: "Artificial Intelligence and Machine Learning",
        details: [
          "Cursor",
          "RLHF Workflows",
          "AI code review",
          "Code optimisation",
        ],
        unlocked: false,
        gameType: "memory",
        gameData: {
          crossword: [
            {
              word: "DIV",
              hint: "Iterative way of building software with quick feedback cycles (Scrum/Kanban)",
            },
            {
              word: "TAG",
              hint: "Instructions written in a programming language to build software",
            },
            {
              word: "CONST",
              hint: "A computer or system that provides data or services to other computers",
            },
            {
              word: "CURLY",
              hint: "A set of rules that allows different software systems to communicate",
            },
          ],
          architectureLayers: [
            { layerPosition: 0, description: "", icon: "" },
            { layerPosition: 1, description: "", icon: "" },
            { layerPosition: 2, description: "", icon: "" },
          ],
          matchThree: [
            { colour: "mediumpurple", icon: "Server" },
            { colour: "green", icon: "Node" },
            { colour: "crimson", icon: "JSON" },
            { colour: "cornflowerblue", icon: "PGSQL" },
            { colour: "darkorange", icon: "Java" },
          ],
          memoryMatch: ["Node", "Java", "System", "SQL", "REST", "GraphQL"],
        },
        targetScore: 1000,
      },
      {
        id: "aws-cloud-comp",
        title: "Cloud Computing with AWS",
        description: "Artificial Intelligence and Machine Learning",
        details: [
          "Lambda",
          "ECS",
          "EC2",
          "Elastic Beanstalk",
          "S3",
          "Cognito",
          "CloudFormation",
          "API Gateway",
          "SES",
          "RDS",
        ],
        unlocked: false,
        gameType: "memory",
        gameData: {
          crossword: [
            {
              word: "DIV",
              hint: "Iterative way of building software with quick feedback cycles (Scrum/Kanban)",
            },
            {
              word: "TAG",
              hint: "Instructions written in a programming language to build software",
            },
            {
              word: "CONST",
              hint: "A computer or system that provides data or services to other computers",
            },
            {
              word: "CURLY",
              hint: "A set of rules that allows different software systems to communicate",
            },
          ],
          architectureLayers: [
            { layerPosition: 0, description: "", icon: "" },
            { layerPosition: 1, description: "", icon: "" },
            { layerPosition: 2, description: "", icon: "" },
          ],
          matchThree: [
            { colour: "mediumpurple", icon: "Server" },
            { colour: "green", icon: "Node" },
            { colour: "crimson", icon: "JSON" },
            { colour: "cornflowerblue", icon: "PGSQL" },
            { colour: "darkorange", icon: "Java" },
          ],
          memoryMatch: ["Node", "Java", "System", "SQL", "REST", "GraphQL"],
        },
        targetScore: 1000,
      },
      {
        id: "proj-man-collab",
        title: "Project Management & Collaboration",
        description: "Artificial Intelligence and Machine Learning",
        details: [
          "Jira",
          "Kanban",
          "Confluence",
          "Miro",
          "Agile methodologies & ceremonies",
          "Baclog Refinement",
          "Flow Metrics",
        ],
        unlocked: false,
        gameType: "memory",
        gameData: {
          crossword: [
            {
              word: "DIV",
              hint: "Iterative way of building software with quick feedback cycles (Scrum/Kanban)",
            },
            {
              word: "TAG",
              hint: "Instructions written in a programming language to build software",
            },
            {
              word: "CONST",
              hint: "A computer or system that provides data or services to other computers",
            },
            {
              word: "CURLY",
              hint: "A set of rules that allows different software systems to communicate",
            },
          ],
          architectureLayers: [
            { layerPosition: 0, description: "", icon: "" },
            { layerPosition: 1, description: "", icon: "" },
            { layerPosition: 2, description: "", icon: "" },
          ],
          matchThree: [
            { colour: "mediumpurple", icon: "Server" },
            { colour: "green", icon: "Node" },
            { colour: "crimson", icon: "JSON" },
            { colour: "cornflowerblue", icon: "PGSQL" },
            { colour: "darkorange", icon: "Java" },
          ],
          memoryMatch: ["Node", "Java", "System", "SQL", "REST", "GraphQL"],
        },
        targetScore: 1000,
      },
    ],
  },
  {
    id: "education",
    name: KingdomName.Education,
    description: "Academic achievements",
    icon: GraduationCap,
    colour: "from-emerald-500 to-green-600",
    position: { angle: 180, distance: 240 },
    missions: [
      {
        id: "software-eng",
        title: "Systems Development NQF 5",
        description: "WeThinkCode_",
        details: [
          "Focus on algorithms and data structures",
          "Software engineering principles",
          "Database systems and design",
        ],
        date: "2019 - 2022",
        unlocked: false,
        gameType: "crossword",
        gameData: {
          crossword: [
            {
              word: "STAR",
              hint: "A massive glowing sphere of plasma powered by nuclear fusion",
            },
            {
              word: "BLOEM",
              hint: "Nickname for Bloemfontein, the 'City of Roses', also known for its birdlife",
            },
            {
              word: "CALCULUS",
              hint: "Mathematics used to study change, motion, and rates in physics",
            },
            {
              word: "UNIVERSE",
              hint: "Everything that exists: space, time, matter, and energy",
            },
          ],
          architectureLayers: [
            { layerPosition: 0, description: "", icon: "" },
            { layerPosition: 0, description: "", icon: "" },
            { layerPosition: 0, description: "", icon: "" },
          ],
          matchThree: [
            { colour: "green", icon: "Calculator" },
            { colour: "slateblue", icon: "Telescope" },
            { colour: "darkviolet", icon: "Galaxy" },
            { colour: "crimson", icon: "Formula" },
            { colour: "darkorange", icon: "Rocket" },
            { colour: "cornflowerblue", icon: "Experiment" },
          ],
          memoryMatch: [
            "Rocket",
            "Telescope",
            "Experiment",
            "Galaxy",
            "Satellite",
            "GraphQL",
          ],
        },
        targetScore: 1000,
      },
      {
        id: "bsc-phys-astro",
        title: "BSc Physics & Astrophysics",
        description: "University of the Free State",
        details: [
          "Focus on algorithms and data structures",
          "Software engineering principles",
          "Database systems and design",
        ],
        date: "2019 - 2022",
        unlocked: false,
        gameType: "crossword",
        gameData: {
          crossword: [
            {
              word: "STAR",
              hint: "A massive glowing sphere of plasma powered by nuclear fusion",
            },
            {
              word: "BLOEM",
              hint: "Nickname for Bloemfontein, the 'City of Roses', also known for its birdlife",
            },
            {
              word: "CALCULUS",
              hint: "Mathematics used to study change, motion, and rates in physics",
            },
            {
              word: "UNIVERSE",
              hint: "Everything that exists: space, time, matter, and energy",
            },
          ],
          architectureLayers: [
            { layerPosition: 0, description: "", icon: "" },
            { layerPosition: 0, description: "", icon: "" },
            { layerPosition: 0, description: "", icon: "" },
          ],
          matchThree: [
            { colour: "green", icon: "Calculator" },
            { colour: "slateblue", icon: "Telescope" },
            { colour: "darkviolet", icon: "Galaxy" },
            { colour: "crimson", icon: "Formula" },
            { colour: "darkorange", icon: "Rocket" },
            { colour: "cornflowerblue", icon: "Experiment" },
          ],
          memoryMatch: [
            "Rocket",
            "Telescope",
            "Experiment",
            "Galaxy",
            "Satellite",
            "GraphQL",
          ],
        },
        targetScore: 1000,
      },
      {
        id: "nsc-wghs",
        title: "National Senior Certificate",
        description: "Wynberg Girls' High School",
        details: [
          "Focus on algorithms and data structures",
          "Software engineering principles",
          "Database systems and design",
        ],
        date: "2019 - 2022",
        unlocked: false,
        gameType: "crossword",
        gameData: {
          crossword: [
            {
              word: "STAR",
              hint: "A massive glowing sphere of plasma powered by nuclear fusion",
            },
            {
              word: "BLOEM",
              hint: "Nickname for Bloemfontein, the 'City of Roses', also known for its birdlife",
            },
            {
              word: "CALCULUS",
              hint: "Mathematics used to study change, motion, and rates in physics",
            },
            {
              word: "UNIVERSE",
              hint: "Everything that exists: space, time, matter, and energy",
            },
          ],
          architectureLayers: [
            { layerPosition: 0, description: "", icon: "" },
            { layerPosition: 0, description: "", icon: "" },
            { layerPosition: 0, description: "", icon: "" },
          ],
          matchThree: [
            { colour: "green", icon: "Calculator" },
            { colour: "slateblue", icon: "Telescope" },
            { colour: "darkviolet", icon: "Galaxy" },
            { colour: "crimson", icon: "Formula" },
            { colour: "darkorange", icon: "Rocket" },
            { colour: "cornflowerblue", icon: "Experiment" },
          ],
          memoryMatch: [
            "Rocket",
            "Telescope",
            "Experiment",
            "Galaxy",
            "Satellite",
            "GraphQL",
          ],
        },
        targetScore: 1000,
      },
    ],
  },
  {
    id: "certifications",
    name: KingdomName.Certifications,
    description: "Credentials and awards",
    icon: Crown,
    colour: "from-yellow-500 to-amber-600",
    position: { angle: 240, distance: 240 },
    missions: [
      {
        id: "aws-cloud",
        title: "AWS Certified Cloud Practitioner",
        description: "Amazon Web Services certification",
        details: [
          "Cloud concepts and AWS core services",
          "Security and compliance",
          "Billing and pricing models",
        ],
        date: "2024",
        links: [{ label: "View Credential", url: "#" }],
        unlocked: false,
        gameType: "memory",
        gameData: {
          crossword: [
            {
              word: "DEPLOY",
              hint: "To release an application or service into a live environment",
            },
            {
              word: "USERS",
              hint: "People or identities that access AWS resources through IAM",
            },
            {
              word: "CLOUD",
              hint: "On-demand computing resources delivered over the internet",
            },
            {
              word: "AWS",
              hint: "Amazon Web Services, a major provider of cloud computing services",
            },
          ],

          architectureLayers: [
            { layerPosition: 0, description: "", icon: "" },
            { layerPosition: 0, description: "", icon: "" },
            { layerPosition: 0, description: "", icon: "" },
          ],
          matchThree: [
            { colour: "darkorange", icon: "AWS" },
            { colour: "cornflowerblue", icon: "Cloud" },
            { colour: "green", icon: "S3" },
            { colour: "crimson", icon: "IAM" },
            { colour: "dodgerblue", icon: "Dynamodb" },
          ],
          memoryMatch: ["AWS", "Cloud", "S3", "EC2", "Lambda", "IAM"],
        },
        targetScore: 1000,
      },
      {
        id: "ibm-ux",
        title: "User Experience Design Fundamentals",
        description: "Amazon Web Services certification",
        details: [
          "Cloud concepts and AWS core services",
          "Security and compliance",
          "Billing and pricing models",
        ],
        date: "2024",
        links: [{ label: "View Credential", url: "#" }],
        unlocked: false,
        gameType: "memory",
        gameData: {
          crossword: [
            {
              word: "DEPLOY",
              hint: "To release an application or service into a live environment",
            },
            {
              word: "USERS",
              hint: "People or identities that access AWS resources through IAM",
            },
            {
              word: "CLOUD",
              hint: "On-demand computing resources delivered over the internet",
            },
            {
              word: "AWS",
              hint: "Amazon Web Services, a major provider of cloud computing services",
            },
          ],

          architectureLayers: [
            { layerPosition: 0, description: "", icon: "" },
            { layerPosition: 0, description: "", icon: "" },
            { layerPosition: 0, description: "", icon: "" },
          ],
          matchThree: [
            { colour: "darkorange", icon: "AWS" },
            { colour: "cornflowerblue", icon: "Cloud" },
            { colour: "green", icon: "S3" },
            { colour: "crimson", icon: "IAM" },
            { colour: "dodgerblue", icon: "Dynamodb" },
          ],
          memoryMatch: ["AWS", "Cloud", "S3", "EC2", "Lambda", "IAM"],
        },
        targetScore: 1000,
      },
      {
        id: "ibm-proj-man",
        title: "Project Management Fundamentals",
        description: "IBM SkillsBuild Certification",
        details: [
          "Cloud concepts and AWS core services",
          "Security and compliance",
          "Billing and pricing models",
        ],
        date: "2024",
        links: [{ label: "View Credential", url: "#" }],
        unlocked: false,
        gameType: "memory",
        gameData: {
          crossword: [
            {
              word: "DEPLOY",
              hint: "To release an application or service into a live environment",
            },
            {
              word: "USERS",
              hint: "People or identities that access AWS resources through IAM",
            },
            {
              word: "CLOUD",
              hint: "On-demand computing resources delivered over the internet",
            },
            {
              word: "AWS",
              hint: "Amazon Web Services, a major provider of cloud computing services",
            },
          ],

          architectureLayers: [
            { layerPosition: 0, description: "", icon: "" },
            { layerPosition: 0, description: "", icon: "" },
            { layerPosition: 0, description: "", icon: "" },
          ],
          matchThree: [
            { colour: "darkorange", icon: "AWS" },
            { colour: "cornflowerblue", icon: "Cloud" },
            { colour: "green", icon: "S3" },
            { colour: "crimson", icon: "IAM" },
            { colour: "dodgerblue", icon: "Dynamodb" },
          ],
          memoryMatch: ["AWS", "Cloud", "S3", "EC2", "Lambda", "IAM"],
        },
        targetScore: 1000,
      },
    ],
  },
  {
    id: "exploring",
    name: KingdomName.Exploring,
    description: "Currently learning",
    icon: Compass,
    colour: "from-rose-500 to-pink-600",
    position: { angle: 300, distance: 240 },
    missions: [
      {
        id: "graphql",
        title: "GraphQL Fundamentals",
        description: "Build flexible APIs with queries, mutations, and schemas",
        details: [
          "Schema & types",
          "Queries and mutations",
          "Resolvers & caching basics",
        ],
        unlocked: false,
        gameType: "crossword",
        gameData: {
          crossword: [
            {
              word: "SCHEMA",
              hint: "The contract that defines types and operations in a GraphQL API",
            },
            {
              word: "QUERY",
              hint: "Used to read/fetch data from a GraphQL server",
            },
            {
              word: "MUTATION",
              hint: "Used to create, update, or delete data in GraphQL",
            },
            {
              word: "RESOLVER",
              hint: "A function that returns the data for a field",
            },
          ],
          architectureLayers: [
            { layerPosition: 0, description: "", icon: "" },
            { layerPosition: 0, description: "", icon: "" },
            { layerPosition: 0, description: "", icon: "" },
          ],
          matchThree: [
            { colour: "magenta", icon: "GraphQL" },
            { colour: "green", icon: "Shopify" },
            { colour: "red", icon: "Netflix" },
            { colour: "dodgerblue", icon: "Facebook" },
            { colour: "mediumpurple", icon: "GitHub" },
          ],
          memoryMatch: ["AWS", "Cloud", "S3", "EC2", "Lambda", "IAM"],
        },
        targetScore: 1000,
      },
    ],
  },
];
